"""add billing collection fields to billing_entries

Revision ID: 2816d50166a3
Revises: a2c7dfb1fad5
Create Date: 2026-09-20 22:02:43.997311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2816d50166a3'
down_revision: Union[str, None] = 'a2c7dfb1fad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    billing_payment_status = sa.Enum('pending', 'paid', 'waived', name='billing_payment_status')
    billing_payment_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'billing_entries',
        sa.Column(
            'payment_status',
            billing_payment_status,
            nullable=False,
            server_default='pending',
        ),
    )
    op.add_column('billing_entries', sa.Column('receipt_number', sa.String(length=60), nullable=True))
    op.add_column('billing_entries', sa.Column('collected_by', sa.UUID(), nullable=True))
    op.add_column('billing_entries', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_billing_entries_payment_status'), 'billing_entries', ['payment_status'], unique=False)
    op.create_foreign_key(op.f('fk_billing_entries_collected_by_users'), 'billing_entries', 'users', ['collected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_billing_entries_collected_by_users'), 'billing_entries', type_='foreignkey')
    op.drop_index(op.f('ix_billing_entries_payment_status'), table_name='billing_entries')
    op.drop_column('billing_entries', 'paid_at')
    op.drop_column('billing_entries', 'collected_by')
    op.drop_column('billing_entries', 'receipt_number')
    op.drop_column('billing_entries', 'payment_status')
    sa.Enum(name='billing_payment_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
