"""add staff_salaries table

Revision ID: 71a6922ac204
Revises: 2816d50166a3
Create Date: 2026-09-21 02:10:03.446171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a6922ac204'
down_revision: Union[str, None] = '2816d50166a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_salaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='salary_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], name=op.f('fk_staff_salaries_paid_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_salaries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_salaries')),
    sa.UniqueConstraint('user_id', 'period', name='uq_staff_salary_user_period')
    )
    op.create_index(op.f('ix_staff_salaries_status'), 'staff_salaries', ['status'], unique=False)
    op.create_index(op.f('ix_staff_salaries_user_id'), 'staff_salaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_salaries_user_id'), table_name='staff_salaries')
    op.drop_index(op.f('ix_staff_salaries_status'), table_name='staff_salaries')
    op.drop_table('staff_salaries')
    # ### end Alembic commands ###
