"""add notes to vitals

Revision ID: a2c7dfb1fad5
Revises: e9c3b3ff14d2
Create Date: 2026-09-09 23:20:25.190018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c7dfb1fad5'
down_revision: Union[str, None] = 'e9c3b3ff14d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitals', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vitals', 'notes')
    # ### end Alembic commands ###
