"""add pricing and payment tracking to test catalogue and orders

Revision ID: ffec5762c57f
Revises: 71a6922ac204
Create Date: 2026-09-22 02:57:20.269825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffec5762c57f'
down_revision: Union[str, None] = '71a6922ac204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_catalogue', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('test_orders', sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0'))

    lab_payment_status = sa.Enum('pending', 'paid', 'waived', name='lab_payment_status')
    lab_payment_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'test_orders',
        sa.Column('payment_status', lab_payment_status, nullable=False, server_default='pending'),
    )
    op.add_column('test_orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_orders', sa.Column('collected_by', sa.UUID(), nullable=True))
    op.add_column('test_orders', sa.Column('receipt_number', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_test_orders_payment_status'), 'test_orders', ['payment_status'], unique=False)
    op.create_foreign_key(op.f('fk_test_orders_collected_by_users'), 'test_orders', 'users', ['collected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_orders_collected_by_users'), 'test_orders', type_='foreignkey')
    op.drop_index(op.f('ix_test_orders_payment_status'), table_name='test_orders')
    op.drop_column('test_orders', 'receipt_number')
    op.drop_column('test_orders', 'collected_by')
    op.drop_column('test_orders', 'paid_at')
    op.drop_column('test_orders', 'payment_status')
    sa.Enum(name='lab_payment_status').drop(op.get_bind(), checkfirst=True)
    op.drop_column('test_orders', 'amount')
    op.drop_column('test_catalogue', 'price')
    # ### end Alembic commands ###
